Repository githubschool/automatic-pancake, pull requests merged in 2022-04, with the labels that each got.

#14 Update allthedoll's slide
  _slides/02-allthedoll.md
Labels: enhancement, unicorn

#15 Alter caption Cpt-Falcon slides
  _slides/05-Cpt-Falcon.md
Labels: documentation, unicorn

#13 Update m4k0m1's slide
  _slides/09-m4k0m1.md
Labels: enhancement

#18 Update the srinivaskang's slide
  _slides/16-srinivaskang.md
Labels: enhancement

#19 Caption my slide
  _slides/15-sowright85.md
Labels: documentation

#17 Update antonyken's slide
  _slides/04-AntonyKen.md
Labels: enhancement

#12 update anoushkashishodia's slide
  _slides/03-Anoushkashishodia.md
Labels: enhancement
